- name: Installing stow
  apt:
    name: stow
  become: true
  tags:
    - install
    - dotfiles
    - stow

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: "https://github.com/vukovuko/.dotfiles"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  become: true
  become_user: thevuko
  tags:
    - install
    - dotfiles
    - stow

- name: Ensure ubuntu script is executable
  file:
    path: "{{ lookup('env', 'HOME') }}/.dotfiles/ubuntu"
    mode: "0755"
    state: file
  become: true
  become_user: thevuko
  tags:
    - install
    - dotfiles
    - stow

- name: Ensure install script is executable
  file:
    path: "{{ lookup('env', 'HOME') }}/.dotfiles/install"
    mode: "0755"
    state: file
  become: true
  become_user: thevuko
  tags:
    - install
    - dotfiles
    - stow

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./ubuntu
  become: true
  become_user: thevuko
  tags:
    - install
    - dotfiles
    - stow
