- name: Install tmux
  become: true
  apt:
    name: tmux
    state: present
  tags:
    - install
    - tmux

- name: Clone TPM repository
  become: true
  become_user: thevuko
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm.git"
    dest: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"
  tags:
    - install
    - tmux
